<a href="https://colab.research.google.com/github/ChetanGoud77/PYTHON/blob/main/DAY_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
k=[4,2.56789,9,87.9999,40,'HYDERABAD']

In [ ]:
k

[4, 2.56789, 9, 87.9999, 40, 'HYDERABAD']

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
pd.Series(k)

0            4
1      2.56789
2            9
3      87.9999
4           40
5    HYDERABAD
dtype: object

In [ ]:
k=[4,2.56789,9,87.9999,40]

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
pd.Series(k)

0     4.00000
1     2.56789
2     9.00000
3    87.99990
4    40.00000
dtype: float64

In [ ]:
a=np.random.randint(20,50,15)
a

array([40, 49, 40, 27, 44, 42, 30, 31, 45, 38, 33, 40, 36, 46, 31])

In [ ]:
a.ndim

2

In [ ]:
pd.Series(a)

0     40
1     49
2     40
3     27
4     44
5     42
6     30
7     31
8     45
9     38
10    33
11    40
12    36
13    46
14    31
dtype: int64

In [17]:
a[4:9]

array([44, 42, 30, 31, 45])

In [16]:
b=np.random.randint(100,200,(6,5))
b

array([[165, 144, 141, 153, 143],
       [170, 106, 187, 176, 132],
       [130, 100, 128, 105, 196],
       [187, 197, 108, 161, 190],
       [131, 105, 154, 179, 179],
       [115, 117, 136, 165, 184]])

In [18]:
np.random.seed(77)
b=np.random.randint(100,200,(6,5))
b

array([[187, 195, 184, 184, 137],
       [124, 131, 196, 157, 139],
       [144, 119, 132, 159, 154],
       [136, 147, 178, 115, 110],
       [171, 135, 159, 101, 111],
       [181, 106, 120, 156, 197]])

In [19]:
b.shape

(6, 5)

In [44]:
pd.DataFrame(b)

     0    1    2    3    4
0  187  195  184  184  137
1  124  131  196  157  139
2  144  119  132  159  154
3  136  147  178  115  110
4  171  135  159  101  111
5  181  106  120  156  197

In [45]:
pd.DataFrame(b,columns=['A','B','C','D','E'])

     A    B    C    D    E
0  187  195  184  184  137
1  124  131  196  157  139
2  144  119  132  159  154
3  136  147  178  115  110
4  171  135  159  101  111
5  181  106  120  156  197

In [53]:
pd.DataFrame(b,columns=['name','age','class','address','pincode'],index=['a','b','c','d','e','f'])

   name  age  class  address  pincode
a   187  195    184      184      137
b   124  131    196      157      139
c   144  119    132      159      154
d   136  147    178      115      110
e   171  135    159      101      111
f   181  106    120      156      197

In [54]:
df.iloc[0,0]

0.6735654581007056